/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterTopCandidatesRouteImport } from './routes/recruiter.top-candidates'
import { Route as RecruiterSettingsRouteImport } from './routes/recruiter.settings'
import { Route as RecruiterPipelineRouteImport } from './routes/recruiter.pipeline'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter.jobs'
import { Route as RecruiterInterviewsRouteImport } from './routes/recruiter.interviews'
import { Route as RecruiterEmailsRouteImport } from './routes/recruiter.emails'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter.dashboard'
import { Route as RecruiterApplicantsRouteImport } from './routes/recruiter.applicants'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter.analytics'
import { Route as CandidateSettingsRouteImport } from './routes/candidate.settings'
import { Route as CandidateResumeAnalysisRouteImport } from './routes/candidate.resume-analysis'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateJobsRouteImport } from './routes/candidate.jobs'
import { Route as CandidateInterviewsRouteImport } from './routes/candidate.interviews'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as RecruiterJobsCreateRouteImport } from './routes/recruiter.jobs.create'
import { Route as CandidateJobsIdRouteImport } from './routes/candidate.jobs.$id'
import { Route as CandidateJobsIdApplyRouteImport } from './routes/candidate.jobs.$id.apply'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterTopCandidatesRoute = RecruiterTopCandidatesRouteImport.update({
  id: '/recruiter/top-candidates',
  path: '/recruiter/top-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterSettingsRoute = RecruiterSettingsRouteImport.update({
  id: '/recruiter/settings',
  path: '/recruiter/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterPipelineRoute = RecruiterPipelineRouteImport.update({
  id: '/recruiter/pipeline',
  path: '/recruiter/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/recruiter/jobs',
  path: '/recruiter/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterInterviewsRoute = RecruiterInterviewsRouteImport.update({
  id: '/recruiter/interviews',
  path: '/recruiter/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterEmailsRoute = RecruiterEmailsRouteImport.update({
  id: '/recruiter/emails',
  path: '/recruiter/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/recruiter/dashboard',
  path: '/recruiter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterApplicantsRoute = RecruiterApplicantsRouteImport.update({
  id: '/recruiter/applicants',
  path: '/recruiter/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/recruiter/analytics',
  path: '/recruiter/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSettingsRoute = CandidateSettingsRouteImport.update({
  id: '/candidate/settings',
  path: '/candidate/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateResumeAnalysisRoute = CandidateResumeAnalysisRouteImport.update({
  id: '/candidate/resume-analysis',
  path: '/candidate/resume-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateJobsRoute = CandidateJobsRouteImport.update({
  id: '/candidate/jobs',
  path: '/candidate/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateInterviewsRoute = CandidateInterviewsRouteImport.update({
  id: '/candidate/interviews',
  path: '/candidate/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsCreateRoute = RecruiterJobsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RecruiterJobsRoute,
} as any)
const CandidateJobsIdRoute = CandidateJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidateJobsRoute,
} as any)
const CandidateJobsIdApplyRoute = CandidateJobsIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CandidateJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/jobs': typeof CandidateJobsRouteWithChildren
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume-analysis': typeof CandidateResumeAnalysisRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applicants': typeof RecruiterApplicantsRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/emails': typeof RecruiterEmailsRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/top-candidates': typeof RecruiterTopCandidatesRoute
  '/candidate/jobs/$id': typeof CandidateJobsIdRouteWithChildren
  '/recruiter/jobs/create': typeof RecruiterJobsCreateRoute
  '/candidate/jobs/$id/apply': typeof CandidateJobsIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/jobs': typeof CandidateJobsRouteWithChildren
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume-analysis': typeof CandidateResumeAnalysisRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applicants': typeof RecruiterApplicantsRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/emails': typeof RecruiterEmailsRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/top-candidates': typeof RecruiterTopCandidatesRoute
  '/candidate/jobs/$id': typeof CandidateJobsIdRouteWithChildren
  '/recruiter/jobs/create': typeof RecruiterJobsCreateRoute
  '/candidate/jobs/$id/apply': typeof CandidateJobsIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/jobs': typeof CandidateJobsRouteWithChildren
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume-analysis': typeof CandidateResumeAnalysisRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/applicants': typeof RecruiterApplicantsRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/emails': typeof RecruiterEmailsRoute
  '/recruiter/interviews': typeof RecruiterInterviewsRoute
  '/recruiter/jobs': typeof RecruiterJobsRouteWithChildren
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/top-candidates': typeof RecruiterTopCandidatesRoute
  '/candidate/jobs/$id': typeof CandidateJobsIdRouteWithChildren
  '/recruiter/jobs/create': typeof RecruiterJobsCreateRoute
  '/candidate/jobs/$id/apply': typeof CandidateJobsIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/auth/callback'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/interviews'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/resume-analysis'
    | '/candidate/settings'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/dashboard'
    | '/recruiter/emails'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/pipeline'
    | '/recruiter/settings'
    | '/recruiter/top-candidates'
    | '/candidate/jobs/$id'
    | '/recruiter/jobs/create'
    | '/candidate/jobs/$id/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/auth/callback'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/interviews'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/resume-analysis'
    | '/candidate/settings'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/dashboard'
    | '/recruiter/emails'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/pipeline'
    | '/recruiter/settings'
    | '/recruiter/top-candidates'
    | '/candidate/jobs/$id'
    | '/recruiter/jobs/create'
    | '/candidate/jobs/$id/apply'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/auth/callback'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/interviews'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/resume-analysis'
    | '/candidate/settings'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/dashboard'
    | '/recruiter/emails'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/pipeline'
    | '/recruiter/settings'
    | '/recruiter/top-candidates'
    | '/candidate/jobs/$id'
    | '/recruiter/jobs/create'
    | '/candidate/jobs/$id/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateInterviewsRoute: typeof CandidateInterviewsRoute
  CandidateJobsRoute: typeof CandidateJobsRouteWithChildren
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResumeAnalysisRoute: typeof CandidateResumeAnalysisRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterApplicantsRoute: typeof RecruiterApplicantsRoute
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  RecruiterEmailsRoute: typeof RecruiterEmailsRoute
  RecruiterInterviewsRoute: typeof RecruiterInterviewsRoute
  RecruiterJobsRoute: typeof RecruiterJobsRouteWithChildren
  RecruiterPipelineRoute: typeof RecruiterPipelineRoute
  RecruiterSettingsRoute: typeof RecruiterSettingsRoute
  RecruiterTopCandidatesRoute: typeof RecruiterTopCandidatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/top-candidates': {
      id: '/recruiter/top-candidates'
      path: '/recruiter/top-candidates'
      fullPath: '/recruiter/top-candidates'
      preLoaderRoute: typeof RecruiterTopCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/settings': {
      id: '/recruiter/settings'
      path: '/recruiter/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof RecruiterSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/pipeline': {
      id: '/recruiter/pipeline'
      path: '/recruiter/pipeline'
      fullPath: '/recruiter/pipeline'
      preLoaderRoute: typeof RecruiterPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/recruiter/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/interviews': {
      id: '/recruiter/interviews'
      path: '/recruiter/interviews'
      fullPath: '/recruiter/interviews'
      preLoaderRoute: typeof RecruiterInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/emails': {
      id: '/recruiter/emails'
      path: '/recruiter/emails'
      fullPath: '/recruiter/emails'
      preLoaderRoute: typeof RecruiterEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/recruiter/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/applicants': {
      id: '/recruiter/applicants'
      path: '/recruiter/applicants'
      fullPath: '/recruiter/applicants'
      preLoaderRoute: typeof RecruiterApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/recruiter/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/candidate/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/resume-analysis': {
      id: '/candidate/resume-analysis'
      path: '/candidate/resume-analysis'
      fullPath: '/candidate/resume-analysis'
      preLoaderRoute: typeof CandidateResumeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/jobs': {
      id: '/candidate/jobs'
      path: '/candidate/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof CandidateJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/interviews': {
      id: '/candidate/interviews'
      path: '/candidate/interviews'
      fullPath: '/candidate/interviews'
      preLoaderRoute: typeof CandidateInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs/create': {
      id: '/recruiter/jobs/create'
      path: '/create'
      fullPath: '/recruiter/jobs/create'
      preLoaderRoute: typeof RecruiterJobsCreateRouteImport
      parentRoute: typeof RecruiterJobsRoute
    }
    '/candidate/jobs/$id': {
      id: '/candidate/jobs/$id'
      path: '/$id'
      fullPath: '/candidate/jobs/$id'
      preLoaderRoute: typeof CandidateJobsIdRouteImport
      parentRoute: typeof CandidateJobsRoute
    }
    '/candidate/jobs/$id/apply': {
      id: '/candidate/jobs/$id/apply'
      path: '/apply'
      fullPath: '/candidate/jobs/$id/apply'
      preLoaderRoute: typeof CandidateJobsIdApplyRouteImport
      parentRoute: typeof CandidateJobsIdRoute
    }
  }
}

interface CandidateJobsIdRouteChildren {
  CandidateJobsIdApplyRoute: typeof CandidateJobsIdApplyRoute
}

const CandidateJobsIdRouteChildren: CandidateJobsIdRouteChildren = {
  CandidateJobsIdApplyRoute: CandidateJobsIdApplyRoute,
}

const CandidateJobsIdRouteWithChildren = CandidateJobsIdRoute._addFileChildren(
  CandidateJobsIdRouteChildren,
)

interface CandidateJobsRouteChildren {
  CandidateJobsIdRoute: typeof CandidateJobsIdRouteWithChildren
}

const CandidateJobsRouteChildren: CandidateJobsRouteChildren = {
  CandidateJobsIdRoute: CandidateJobsIdRouteWithChildren,
}

const CandidateJobsRouteWithChildren = CandidateJobsRoute._addFileChildren(
  CandidateJobsRouteChildren,
)

interface RecruiterJobsRouteChildren {
  RecruiterJobsCreateRoute: typeof RecruiterJobsCreateRoute
}

const RecruiterJobsRouteChildren: RecruiterJobsRouteChildren = {
  RecruiterJobsCreateRoute: RecruiterJobsCreateRoute,
}

const RecruiterJobsRouteWithChildren = RecruiterJobsRoute._addFileChildren(
  RecruiterJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateInterviewsRoute: CandidateInterviewsRoute,
  CandidateJobsRoute: CandidateJobsRouteWithChildren,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResumeAnalysisRoute: CandidateResumeAnalysisRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterApplicantsRoute: RecruiterApplicantsRoute,
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  RecruiterEmailsRoute: RecruiterEmailsRoute,
  RecruiterInterviewsRoute: RecruiterInterviewsRoute,
  RecruiterJobsRoute: RecruiterJobsRouteWithChildren,
  RecruiterPipelineRoute: RecruiterPipelineRoute,
  RecruiterSettingsRoute: RecruiterSettingsRoute,
  RecruiterTopCandidatesRoute: RecruiterTopCandidatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
